#ddev-generated
# Simple template to demonstrate ddev-printenv
version: '3.6'
services:
  ddev-printenv:
    container_name: ddev-${DDEV_SITENAME}-ddev-printenv
    image: busybox:stable
    command: tail -f /dev/null
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
